//! Bakes `rules/` and `queries/` into the crate at build time.
//!
//! A shipped binary has no repository beside it, and until T9 `skillmap ci`
//! needed `--rules` pointing at a checkout — which made the tool undistributable
//! and was the one gap standing between T8's check and anybody actually running
//! it.
//!
//! # This does not make rules code
//!
//! Invariant 7 says detection lives in data. It still does: adding a rule is a
//! `.toml` and a `.scm` at the repository root, and this script finds them by
//! walking, never by a list somebody has to remember to update. Nothing here
//! knows what a rule *means*. It copies bytes.
//!
//! # Why the contents are written as literals rather than `include_str!`
//!
//! `include_str!` would leave absolute paths in the generated source. The
//! release build remaps the workspace prefix and strips symbols, so they would
//! probably not survive — but "probably not" is a poor basis for a promise that
//! usernames never reach a published binary, and the whole point of T9's
//! byte-identity check is to stop relying on that kind of reasoning. Emitting
//! escaped literals cannot leak a path at all.

use std::path::{Path, PathBuf};

/// Directories baked in, relative to the workspace root.
const TREES: [&str; 2] = ["rules", "queries"];

fn main() {
    let Some(workspace) = workspace_root() else {
        fail(
            "cannot locate the workspace root from CARGO_MANIFEST_DIR; \
             skillmap-rules must be built from within the skillmap workspace",
        );
    };

    let mut files: Vec<(String, String)> = Vec::new();
    for tree in TREES {
        let dir = workspace.join(tree);
        if !dir.is_dir() {
            // Not a warning. A binary that builds with no rules scans every
            // bundle clean, which is the single worst thing this tool can do,
            // and it would do it silently. Refuse to produce one.
            fail(&format!(
                "{} does not exist. skillmap embeds its rule data at build time, \
                 and a build with no rules would produce a scanner that reports \
                 every project clean.",
                dir.display()
            ));
        }
        collect(&dir, &workspace, &mut files);
    }

    // Sorted, so the generated file is byte-identical between machines whose
    // filesystems enumerate directories in different orders — invariant 2,
    // applied one level below the manifest.
    files.sort();

    let mut generated = String::from(
        "// @generated by build.rs from the workspace `rules/` and `queries/` trees.\n\
         // Repo-relative path, then contents.\n\
         pub(crate) static FILES: &[(&str, &str)] = &[\n",
    );
    for (path, text) in &files {
        // `{:?}` on a &str emits a valid Rust string literal for any UTF-8
        // input, which is exactly the escaping needed and not worth hand-rolling.
        generated.push_str(&format!("    ({path:?}, {text:?}),\n"));
    }
    generated.push_str("];\n");

    let Ok(out_dir) = std::env::var("OUT_DIR") else {
        fail("OUT_DIR is not set; this must run as a Cargo build script");
    };
    let destination = Path::new(&out_dir).join("embedded.rs");
    if std::fs::write(&destination, generated).is_err() {
        fail(&format!("cannot write {}", destination.display()));
    }
}

/// The workspace root: two levels above `crates/skillmap-rules`.
fn workspace_root() -> Option<PathBuf> {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").ok()?;
    Path::new(&manifest)
        .parent()?
        .parent()
        .map(Path::to_path_buf)
}

/// Every file beneath `dir`, recorded relative to `workspace` with forward
/// slashes.
///
/// Each file gets its own `rerun-if-changed`, and so does every directory.
/// Directory watches alone catch additions and deletions but not edits; file
/// watches alone catch edits but not a newly added rule. Both are needed, and
/// getting this wrong would mean a stale binary silently shipping the rules from
/// whenever it was last built.
fn collect(dir: &Path, workspace: &Path, found: &mut Vec<(String, String)>) {
    println!("cargo:rerun-if-changed={}", dir.display());

    let Ok(entries) = std::fs::read_dir(dir) else {
        fail(&format!("cannot read {}", dir.display()));
    };

    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(&path, workspace, found);
            continue;
        }

        println!("cargo:rerun-if-changed={}", path.display());

        let Ok(relative) = path.strip_prefix(workspace) else {
            continue;
        };
        let Some(relative) = relative.to_str() else {
            fail(&format!("{} is not a valid UTF-8 path", path.display()));
        };

        match std::fs::read_to_string(&path) {
            Ok(text) => found.push((relative.replace('\\', "/"), text)),
            // Rule data is text by definition. A file that is not is either a
            // mistake or something that should not be in these trees.
            Err(error) => fail(&format!(
                "cannot read {} as UTF-8 text: {error}",
                path.display()
            )),
        }
    }
}

/// Stop the build with a message.
///
/// `std::process::exit` rather than `panic!`: the workspace denies `panic` in
/// library crates (invariant 10) and a build script inherits those lints, but
/// more to the point a panic here prints a backtrace nobody needs above the one
/// line that actually explains the problem.
fn fail(message: &str) -> ! {
    eprintln!("skillmap-rules build script: {message}");
    std::process::exit(1)
}
