#!/usr/bin/env bash
#
# Emit the Homebrew formula for a release, on stdout.
#
# Generated from the checksums of the archives that were actually built, never
# hand-edited. A formula with a stale sha256 fails at install time with a hash
# mismatch, which reads to a user exactly like a compromised download — the one
# error message this project must never produce by accident.
#
# The formula belongs in a tap repository (skillmap/homebrew-skillmap), because
# Homebrew resolves `brew install skillmap/skillmap/skillmap` by looking there
# and not here. That repository does not exist yet; until it does the formula is
# attached to each GitHub release, which is enough to install from a local file
# and not enough to call the tap shipped. Recorded in docs/00-tasks.md's Known
# gaps rather than implied by the presence of this script.
#
# Usage:  scripts/homebrew-formula.sh <version> <release-dir>
#
#   <release-dir> holds the archives and a SHA256SUMS file, as produced by the
#   publish job in .github/workflows/release.yml.
#
set -euo pipefail

if [ "$#" -ne 2 ]; then
  echo "usage: $0 <version> <release-dir>" >&2
  exit 1
fi

VERSION="$1"
RELEASE="$2"
BASE="https://github.com/skillmap/skillmap/releases/download/v$VERSION"

# Look the checksum up rather than recomputing it: this must agree with the
# SHA256SUMS file published alongside, and computing it twice is two chances to
# publish two different numbers.
#
# The name in SHA256SUMS may carry a `./` prefix and, in binary mode, a leading
# `*` on the filename field. Both are normalized rather than matched literally —
# which spelling appears depends on the coreutils build, and a lookup that
# silently found nothing is how the first version of this script emitted a
# complete formula with four empty sha256 fields.
checksum() {
  local archive="$1"
  local found
  found=$(
    awk -v want="$archive" '
      { name = $2; sub(/^\*/, "", name); sub(/^\.\//, "", name)
        if (name == want) { print $1; exit } }
    ' "$RELEASE/SHA256SUMS"
  )
  if [ -z "$found" ]; then
    echo "homebrew-formula.sh: $archive is not in $RELEASE/SHA256SUMS" >&2
    return 1
  fi
  printf '%s' "$found"
}

# Resolved before the template, not inside it. `$(checksum …)` in a heredoc runs
# in a subshell, so a failure there cannot stop the heredoc — the script would
# print a formula whose hashes are empty strings and exit 0. A published formula
# with a wrong hash fails at install time with a checksum mismatch, which reads
# to a user exactly like a compromised download.
DARWIN_ARM64="$(checksum skillmap-darwin-arm64.tar.gz)"
DARWIN_X64="$(checksum skillmap-darwin-x64.tar.gz)"
LINUX_ARM64="$(checksum skillmap-linux-arm64.tar.gz)"
LINUX_X64="$(checksum skillmap-linux-x64.tar.gz)"

cat <<FORMULA
# Generated by scripts/homebrew-formula.sh. Do not edit by hand.
class Skillmap < Formula
  desc "Capability differ for AI agent skills"
  homepage "https://github.com/skillmap/skillmap"
  version "$VERSION"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "$BASE/skillmap-darwin-arm64.tar.gz"
      sha256 "$DARWIN_ARM64"
    end
    on_intel do
      url "$BASE/skillmap-darwin-x64.tar.gz"
      sha256 "$DARWIN_X64"
    end
  end

  on_linux do
    on_arm do
      url "$BASE/skillmap-linux-arm64.tar.gz"
      sha256 "$LINUX_ARM64"
    end
    on_intel do
      url "$BASE/skillmap-linux-x64.tar.gz"
      sha256 "$LINUX_X64"
    end
  end

  def install
    bin.install "skillmap"
  end

  test do
    # Not a version banner. The binary carries its own rules, and a build that
    # embedded none would scan every project clean — so the test asserts it can
    # actually detect something.
    assert_match "skillmap #{version}", shell_output("#{bin}/skillmap version")
    assert_match "credential-read", shell_output("#{bin}/skillmap rules")
  end
end
FORMULA
